name: my_presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  http: ^0.13.5
  image_picker: ^0.8.6
  convex_bottom_bar: ^3.1.0+1
  intl: ^0.17.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  dropdown_search: ^5.0.3
  dio: ^4.0.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

